### ISSUE TITLE
Provide index update service

### ISSUE THREAD

**Issue by forman** [dcs4cop/xcube-smos#7]
The index requires daily updating, need a nightly service that calls   `nckcidx` tool.

**Comment by forman** [comment]
@pont-us, what do you think, is this the same as #3?

**Comment by pont-us** [comment]
> @pont-us, what do you think, is this the same as #3?

Yes, I think so. Since this one is more clearly formulated, I'll close #3 .

**Comment by forman** [comment]
We now use `SmosDirectCatalog` by default, `SmosIndexCatalog` may be deprecated in the future.
Reopen this issue, if we decide something different later.
